sequenceDiagram
    participant Alice
    participant Dan
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Dan: How about you?
    Dan-->>John: Jolly good!
